# Generated by Django 3.1.7 on 2021-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
